### ISSUE TITLE
Issue with Docker, can't get started

### ISSUE THREAD

**Issue by enric1994** [IcaliaLabs/alpha#18]
Hey!

I followed up the Docker Development guide:

1. `git clone https://github.com/IcaliaLabs/alpha.git`
2. `cd alpha`
3. But I get this error when composing up the container: ``docker-compose up web``
```docker-compose up web
Starting alpha_web_1 ... done
Attaching to alpha_web_1
yarn start v0.21.3
$ cross-env NODE_ENV=development node server 
web_1  | sh: 1: cross-env: not found
error Command failed with exit code 127.
alpha_web_1 exited with code 1
```

Thanks!

**Comment by CharlieIGG** [comment]
@enric1994 try running the following:

1. `docker-compose run web bash`
2. `yarn install`
3. `exit`
4. `docker-compose up web`

Let me know if that works for you.

**Comment by enric1994** [comment]
@CharlieIGG it works, ty! But I don't understand why.
The dev.Dockerfile also includes the command `RUN yarn install`

How can this "issue" be corrected? I want to start my container using `docker-compose up -d` and avoid jumping inside the container to install yarn every time.

**Comment by 8masterofpuppets8** [comment]
Having the exact same issue over here - fresh docker install and clone of the repo. The suggested workaround works. Any idea how to get it working without having to access the container every time?

**Comment by CharlieIGG** [comment]
@kurenn think you could take a look at this issue?

**Comment by kurenn** [comment]
I can take a look at it, and see if I can persist the yarn dependencies on image build

**Comment by enric1994** [comment]
Thanks @kurenn !

Closing
