### ISSUE TITLE
Routing broken in live demo

### ISSUE THREAD

**Issue by 8masterofpuppets8** [IcaliaLabs/alpha#20]
I've been playing with this project for a bit and I cannot seem to get the routing to work properly. Based on the code, the route should match any URL (other than home) and return an error page component but it fails if I try to add something to the path. For example:

https://try-alpha.herokuapp.com/test

This throws an error in the console. Whereas this:

http://quotient.icalialabs.com/test

works in the production example. Is something missing from the configuration? I'm new to React :)

**Comment by CharlieIGG** [comment]
Hi @8masterofpuppets8!

This project doesn't really use routing for the time being, and thus the router is not configured (yet).

The reason why the router is included in this project is that we're using https://github.com/react-boilerplate/react-boilerplate as a base, which already came with routing included. You can find out more about configuring routes here: https://github.com/react-boilerplate/react-boilerplate/blob/master/docs/js/routing.md
