### ISSUE TITLE
AWS EC2 installation failed

### ISSUE THREAD

**Issue by inglesuniversal** [IcaliaLabs/alpha#23]
Hi, wonderful script!

I installed the script on an AWS EC2 AMI (Fedora) Instance... and on DOCKER it work ok, however, reading your instructions and using NPM to install the production version, I got this following error:

> Alpha@1.0.0 npmcheckversion /var/www/html/alpha
> node ./internals/scripts/npmcheckversion.js

(node) child_process: options.customFds option is deprecated. Use options.stdio instead.
/var/www/html/alpha/internals/scripts/npmcheckversion.js:5
    throw new Error('[ERROR: React Boilerplate] You need npm version @>=3');
    ^

Error: [ERROR: React Boilerplate] You need npm version @>=3
    at /var/www/html/alpha/internals/scripts/npmcheckversion.js:5:11
    at ChildProcess.exithandler (child_process.js:204:7)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm ERR! weird error 1
npm ERR! not ok code 0
npm ERR! weird error 1
npm ERR! not ok code 0

Hope you can help me find a solution.

And congrats once again

Regards

Hugo Barbosa

**Comment by CharlieIGG** [comment]
Hi @inglesuniversal I think this might be an issue with your Node environment. Have you tried removing and reinstalling node? See here: https://github.com/react-boilerplate/react-boilerplate/issues/694

**Comment by inglesuniversal** [comment]
Thanks CharlieLGG

What I did was to start a fresh Node.js server with AWS (Bitnami) node 10.x.x and I got the code running in NOT TIME....

Now, one thing I am new to node.js is DO I need to keep running that port 3000 all the time or is there a simpler way to keep it live round the clock?

Thanks

Hugo

**Comment by CharlieIGG** [comment]
@inglesuniversal glad to hear you got it working, closing this issue now. 

In regard of your second question, I'm unsure if I understand it correctly, but in practical terms: Yes, you do need to have the webpack server binded to a port in your machine for this work (in development), albeit you should be able to choose any port you wish, see:
[https://webpack.js.org/](https://webpack.js.org/)

In production you can choose to have this served dynamically as well (which does require binding the webpack/express process to a server port), but you can also compile everything and serve this statically, for instance using AWS S3. Look here for more info: [https://github.com/react-boilerplate/react-boilerplate/blob/98f5c0e5bc54a5540466515e38dea9e9cb752019/docs/general/deployment.md](https://github.com/react-boilerplate/react-boilerplate/blob/98f5c0e5bc54a5540466515e38dea9e9cb752019/docs/general/deployment.md)
