### ISSUE TITLE
any wiki available for connecting with dialogflow?

### ISSUE THREAD

**Issue by soorajpazeekal** [IcaliaLabs/alpha#27]
Hi. if any documentation available for integrating with dialogflow?

**Comment by CharlieIGG** [comment]
Hello @soorajpazeekal, we will probably add this in the future, but there's a lot of other overdue maintenance we have to do first.

HINT: take a look at [the Sagas file](app/containers/BotContainer/sagas.js) and [Redux Saga](https://github.com/redux-saga/redux-saga) to see how you can do said connection.

Feel free to Fork and make a PR if you'd like to contribute.
